#!/bin/bash

echo "testing label 1,5"
#for k in 5
#for k in 90 85
#for k in 80 75 70 65 60 55 50 45 40 35 30 25 20 15 10 5 1
for k in 1 5 10 15 80 75 70 65 60 55 50 45 40 35 30 25 20
do
    echo "running with ratio = $k / 1000"
    text_file=binary50_15_150_$k.text
    train_file=binary50_15_150_$k.in
    result_file=binary50_15_150_$k.out
    test_file=test15.in
    ./genbinary15 $k $text_file
    ./filter vectors50 $text_file $train_file 150
    python yelp_cnn.py $train_file $test_file | tee $result_file 
done

#echo $text_file
#echo $train_file
#echo $result_file
